apiVersion: apps/v1
kind: Deployment
metadata:
  name: stx-cicd-demo
spec:
  selector:
    matchLabels:
      app: stx-cicd-demo
  template:
    metadata:
      labels:
        app: stx-cicd-demo
    spec:
      containers:
      - image: registry.local:9001/stx-cicd-demo:latest
        imagePullPolicy: Always
        name: stx-cicd-demo

---
apiVersion: v1
kind: Service
metadata:
  name: stx-cicd-demo
spec:
  selector:
    app: stx-cicd-demo
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 32001
  type: NodePort